### ISSUE TITLE
About the use of software

### ISSUE THREAD

**Issue by baoenzo** [master801/Rune-Factory-Frontier-Tools#1]
[Google translate]
Hello, I have read your guide but it is too hard for a new person like me.
If possible, can you do video tutorials?
I need to extract the file Runefactory.dat to find the language file of the game because I have searched for other folders but I don't see the language file.
I want to translate game language into Vietnamese.
Thank you.

**Comment by master801** [comment]
The `RUNEFACTORY.dat` and `RUNEFACTORY.bin` files are in the game's `files` directory.

So: `files/RUNEFACTORY.dat` & `files/RUNEFACTORY.bin`

You can use Dolphin or some other tool to extract files.

**Comment by baoenzo** [comment]
![image](https://user-images.githubusercontent.com/44154735/72262919-7aa68780-35dd-11ea-8c05-4bb46d9b9327.png)

**Comment by baoenzo** [comment]
I found its language file - text_dat.bin. Is there any way to read it?

**Comment by master801** [comment]
Sorry, I don't know.

All I know is that the encoding is UTF-16BE.
